parameter:
    'num_leaves': [16, 196, 4]
    'max_bin' : [253, 254, 1]
    'lambda_l1': [0.0, 1.0]
    'lambda_l2': [0.0, 1.0]
    'min_data_in_leaf': [20, 500, 10]
    'boosting_type': ['gbdt','goss']
    'learning_rate' : [0.05, 0.25]
    'subsample_for_bin': [20000, 300000, 20000]
    'feature_fraction': [0.4, 1.0]
    'bagging_freq': [1, 7]
    'verbosity' : [0]
    'objective' : ['binary', 'logloss']
    'eval_metric': ['auc', 'binary', 'xentropy']
    'device_type': ['cpu', 'gpu']

constant:
    'max_evals': 1000
    'n_folds': 10
    'num_boost_rounds': 100
    'early_stopping_rounds': 100
    'seed': 47